### ISSUE TITLE
Feature - Silent Mode

### ISSUE THREAD

**Issue by ghost** [kedpter/M3u8Downloader#2]
Hi! I'm using your script to make a script to download some videos from a website. Well, it's working pretty well, the point is the terminal is so dirty. There's a way to hide all informations given and show only the progress bar of segments downloading?

Thanks for the support and for the code, it's helping me a lot!
ps: I loved the thread function, it's amazing, I've made some tests and works really nice.

Edit1: I'm calling the script with CMD and passing the parameters I need. I don't know if this is the best way , but I thinks it's the most easy. If there's another way to use it (and more simple), please tell me.

![MyCode](https://user-images.githubusercontent.com/68434686/89265410-cddc3800-d60a-11ea-88bd-19734959aeed.png)

**Comment by kedpter** [comment]
I added an option '--quiet' to suppress output.
